version: '3'

services:
  web:
    build:
      context: .
    ports:
      - 8000:8000
    env_file: .env
    environment:
      POSTGRES_HOST: 'db'
      REDIS_URL: 'redis://redis:6379'
    volumes:
      - .:/code
    depends_on:
      - db
      - redis
    command: ["node", "app.js"]
  db:
    build: ./db
    env_file: .env
    ports:
      - "5432:5432"
  redis:
    image: redis
    ports:
      - '6379:6379'
